federation_version: 2
subgraphs:
  books:
    routing_url: http://localhost:4001
    schema:
      subgraph_url: http://localhost:4001
      subgraph: books
  reviews:
    routing_url: http://localhost:4002
    schema:
      subgraph_url: http://localhost:4002
      subgraph: reviews
